spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/renren_fast?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: renren
      password: 123456
  redis:
    database: 0
    host: 192.168.1.254
    port: 6379
    password:    # 密码（默认为空）
